Repository treydock/puppet-module-keycloak, pull requests merged in 2019-12, with the labels that each got.

#96 Add support for more client switches
  lib/puppet/type/keycloak_client.rb
  spec/unit/puppet/type/keycloak_client_spec.rb
Labels: enhancement

#98 Add login_theme property to keycloak_client
  lib/puppet/provider/keycloak_client/kcadm.rb
  lib/puppet/type/keycloak_client.rb
  spec/acceptance/5_client_spec.rb
  spec/unit/puppet/type/keycloak_client_spec.rb
Labels: enhancement

#99 Add option to enable tech preview features
  manifests/config.pp
  manifests/init.pp
  spec/classes/init_spec.rb
  spec/spec_helper_local.rb
  templates/profile.properties.erb
Labels: enhancement

#100 Test against Keycloak 8.0.1
  .travis.yml
Labels: enhancement

#101 Fix config.cli to be able to change datasource values
  templates/config.cli.erb
Labels: bugfix

#102 Support Debian 10
  .fixtures.yml
  .sync.yml
  .travis.yml
  CONTRIBUTING.md
  Rakefile
  manifests/init.pp
  metadata.json
  spec/acceptance/nodesets/debian-10.yml
  spec/spec_helper_acceptance_setup.rb
Labels: enhancement

#103 Allow defining supported locales for the realm
  lib/puppet/type/keycloak_realm.rb
  spec/unit/puppet/type/keycloak_realm_spec.rb
Labels: enhancement

#105 Change JAVA_OPTS behavior for Keycloak
  .travis.yml
  manifests/config.pp
  manifests/init.pp
  spec/acceptance/1_class_spec.rb
  spec/classes/init_spec.rb
  templates/keycloak.service.erb
Labels: backwards-incompatible

#90 Change how install_dir is defined, default behavior remains the same
  README.md
  lib/puppet/provider/keycloak_api.rb
  lib/puppet/type/keycloak_api.rb
  manifests/config.pp
  manifests/datasource/mysql.pp
  manifests/datasource/oracle.pp
  manifests/datasource/postgresql.pp
  manifests/init.pp
  manifests/install.pp
  spec/acceptance/99_keycloak_api_spec.rb
Labels: backwards-incompatible

#106 Change default Keycloak version to 8.0.1
  .sync.yml
  .travis.yml
  README.md
  manifests/init.pp
  metadata.json
  spec/classes/init_spec.rb
  spec/spec_helper_acceptance_setup.rb
Labels: backwards-incompatible

#108 Add two new realm properties
  lib/puppet/type/keycloak_realm.rb
  spec/unit/puppet/type/keycloak_realm_spec.rb
Labels: enhancement

#109 Add support for access.token.lifespan client attribute
  lib/puppet/provider/keycloak_client/kcadm.rb
  lib/puppet/type/keycloak_client.rb
Labels: enhancement

#110 Support managing realm flow properties
  lib/puppet/type/keycloak_realm.rb
  spec/unit/puppet/type/keycloak_realm_spec.rb
Labels: enhancement
