Repository treydock/puppet-module-keycloak, pull requests merged in 2019-05, with the labels that each got.

#55 Support managing realm's events config
  lib/puppet/provider/keycloak_realm/kcadm.rb
  lib/puppet/type/keycloak_realm.rb
  spec/acceptance/2_realm_spec.rb
  spec/unit/puppet/provider/keycloak_realm/kcadm_spec.rb
  spec/unit/puppet/type/keycloak_realm_spec.rb
Labels: enhancement

#56 Fix handling of events config during updates
  lib/puppet/provider/keycloak_realm/kcadm.rb
  spec/unit/puppet/provider/keycloak_realm/kcadm_spec.rb
Labels: bug

#59 Postgresql support
  README.md
  manifests/datasource/postgresql.pp
  manifests/init.pp
  templates/config.cli.erb
  templates/database/postgresql/module.xml.erb
Labels: enhancement

#60 Expand postgresql support to behave more like mysql support, simplified a bit
  .fixtures.yml
  README.md
  files/database/postgresql/module.xml
  manifests/datasource/postgresql.pp
  manifests/init.pp
  manifests/params.pp
  metadata.json
  spec/acceptance/1_class_spec.rb
  spec/acceptance/nodesets/centos-7.yml
  spec/classes/init_spec.rb
  spec/spec_helper_acceptance_setup.rb
Labels: enhancement

#61 Set default Keycloak version to 6.0.1
  .sync.yml
  manifests/init.pp
  spec/classes/init_spec.rb
  spec/spec_helper_acceptance_setup.rb
Labels: backwards-incompatible

#62 Use hiera v5 module data
  data/common.yaml
  data/os/Debian.yaml
  data/os/RedHat.yaml
  hiera.yaml
  manifests/datasource/postgresql.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/init_spec.rb
Labels: enhancement

#63 Simplify and consolidate datasource parameters
  .travis.yml
  data/os/Debian.yaml
  data/os/RedHat.yaml
  manifests/datasource/mysql.pp
  manifests/datasource/oracle.pp
  manifests/datasource/postgresql.pp
  manifests/init.pp
Labels: backwards-incompatible
