Repository treydock/puppet-module-keycloak, pull requests merged in 2020-12, with the labels that each got.

#169 PDK Update - Use Github Actions
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .sync.yml
  .travis.yml
  Gemfile
  spec/spec_helper_acceptance_setup.rb
Labels: enhancement

#135 Add convenience wrapper for setting up FreeIPA ldap user providers
  README.md
  manifests/freeipa_user_provider.pp
  spec/acceptance/3_ldap_spec.rb
  spec/defines/freeipa_user_provider_spec.rb
Labels: enhancement

#171 Support saml-group-membership-mapper
  lib/puppet/provider/keycloak_protocol_mapper/kcadm.rb
  lib/puppet/type/keycloak_protocol_mapper.rb
Labels: enhancement

#170 Add convenience define for setting up FreeIPA LDAP mappers
  README.md
  manifests/freeipa_ldap_mappers.pp
  spec/acceptance/3_ldap_spec.rb
  spec/defines/freeipa_ldap_mappers_spec.rb
Labels: enhancement

#172 Fix puppet-lint warning
  manifests/sssd.pp
Labels: bugfix

#173 PDK update
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  Gemfile
  metadata.json
Labels: maintenance

#174 PDK update
  .sync.yml
  Gemfile
  metadata.json
  spec/acceptance/nodesets/centos-8.yml
Labels: maintenance

#176 Support Keycloak 12
  .github/workflows/ci.yaml
  .sync.yml
  README.md
  manifests/init.pp
  metadata.json
Labels: enhancement

#177 Add client_protocol_mappers parameter
  manifests/init.pp
  manifests/resources.pp
Labels: enhancement
