Repository treydock/puppet-module-keycloak, pull requests merged in 2020-02, with the labels that each got.

#118 Support oidc-group-membership-mapper protocol mapper type
  lib/puppet/provider/keycloak_client_protocol_mapper/kcadm.rb
  lib/puppet/provider/keycloak_protocol_mapper/kcadm.rb
  lib/puppet/type/keycloak_client_protocol_mapper.rb
  lib/puppet/type/keycloak_protocol_mapper.rb
  spec/acceptance/6_protocol_mapper_spec.rb
  spec/acceptance/7_client_protocol_mapper_spec.rb
  spec/unit/puppet/type/keycloak_client_protocol_mapper_spec.rb
  spec/unit/puppet/type/keycloak_protocol_mapper_spec.rb
Labels: enhancement

#120 type/keycloak_api: Set install_dir default on /opt/keycloak
  lib/puppet/type/keycloak_api.rb
Labels: bugfix

#121 Add root_url and base_url properties to keycloak_client
  lib/puppet/type/keycloak_client.rb
  spec/acceptance/5_client_spec.rb
  spec/unit/puppet/type/keycloak_client_spec.rb
Labels: enhancement

#122 Support oidc-audience-mapper protocol mapper
  lib/puppet/provider/keycloak_client_protocol_mapper/kcadm.rb
  lib/puppet/provider/keycloak_protocol_mapper/kcadm.rb
  lib/puppet/type/keycloak_client_protocol_mapper.rb
  lib/puppet/type/keycloak_protocol_mapper.rb
  spec/acceptance/6_protocol_mapper_spec.rb
  spec/acceptance/7_client_protocol_mapper_spec.rb
  spec/unit/puppet/type/keycloak_client_protocol_mapper_spec.rb
  spec/unit/puppet/type/keycloak_protocol_mapper_spec.rb
Labels: enhancement

#123 PDK update
  .travis.yml
  Rakefile
  metadata.json
Labels: maintenance

#124 Add sso_session_idle_timeout and sso_session_max_lifespan to keycloak_realm
  lib/puppet/type/keycloak_realm.rb
  spec/acceptance/2_realm_spec.rb
  spec/unit/puppet/type/keycloak_realm_spec.rb
Labels: enhancement

#125 Add access_code_lifespan to keycloak_realm
  lib/puppet/type/keycloak_realm.rb
  spec/acceptance/2_realm_spec.rb
  spec/unit/puppet/type/keycloak_realm_spec.rb
Labels: enhancement

#126 Add access_token_lifespan to keycloak_realm
  lib/puppet/type/keycloak_realm.rb
  spec/acceptance/2_realm_spec.rb
  spec/unit/puppet/type/keycloak_realm_spec.rb
Labels: enhancement
