Repository treydock/puppet-module-keycloak, pull requests merged in 2021-03, with the labels that each got.

#180 Domain mode support
  .fixtures-latest.yml
  .fixtures.yml
  .github/workflows/ci.yaml
  .gitignore
  README.md
  manifests/config.pp
  manifests/init.pp
  manifests/truststore/host.pp
  metadata.json
  spec/acceptance/1_class_spec.rb
  spec/acceptance/1_domain_mode_cluster_spec.rb
  spec/acceptance/nodesets/centos-7-domain-mode-cluster.yml
  spec/classes/init_spec.rb
  spec/spec_helper_acceptance_setup.rb
  templates/config.cli.erb
  templates/keycloak.service.erb
  vagrant/Puppetfile
  vagrant/Vagrantfile
  vagrant/db.pp
  vagrant/install_agent.sh
  vagrant/lb.pp
  vagrant/master.pp
  vagrant/prepare.pp
  vagrant/run_puppet.sh
  vagrant/slave.pp
Labels: enhancement

#183 Improvements to testing, PDK sync some testing code
  .fixtures-latest.yml
  .github/workflows/ci.yaml
  .sync.yml
  spec/acceptance/1_domain_mode_cluster_spec.rb
  spec/acceptance/nodesets/centos-7-domain-mode-cluster.yml
  spec/acceptance/nodesets/centos-7.yml
  spec/acceptance/nodesets/centos-8.yml
  spec/acceptance/nodesets/debian-10.yml
  spec/acceptance/nodesets/debian-9.yml
  spec/acceptance/nodesets/ubuntu-1804.yml
Labels: maintenance

#185 Avoid unnecessary config.cli changes
  templates/config.cli.erb
Labels: bugfix

#184 Drop Puppet 5, support Puppet 7
  .github/workflows/ci.yaml
  .sync.yml
  manifests/service.pp
  metadata.json
  spec/acceptance/1_domain_mode_cluster_spec.rb
  spec/acceptance/nodesets/centos-7-domain-mode-cluster.yml
  spec/spec_helper_acceptance_setup.rb
Labels: backwards-incompatible

#188 Change default Keycloak version to 12.0.4
  .github/workflows/ci.yaml
  .sync.yml
  README.md
  manifests/init.pp
  spec/classes/init_spec.rb
  spec/defines/freeipa_ldap_mappers_spec.rb
  spec/defines/freeipa_user_provider_spec.rb
  spec/defines/spi_deployment_spec.rb
Labels: backwards-incompatible

#187 Split config.cli templates into smaller files, use epp templates
  manifests/config.pp
  spec/classes/init_spec.rb
  templates/config.cli.erb
  templates/config.cli/00-header.epp
  templates/config.cli/01-https-proxy.epp
  templates/config.cli/02-datasource.epp
  templates/config.cli/03-truststore.epp
  templates/config.cli/04-theming.epp
  templates/config.cli/05-deployment-scanner.epp
  templates/config.cli/06-user-cache.epp
  templates/config.cli/10-cluster.epp
  templates/config.cli/11-domain.epp
  templates/config.cli/99-footer.epp
Labels: enhancement

#186 Support Ubuntu 20.04, bump dependency requirements
  .fixtures.yml
  .github/workflows/ci.yaml
  .sync.yml
  README.md
  manifests/init.pp
  metadata.json
  spec/acceptance/nodesets/ubuntu-2004.yml
  spec/spec_helper_acceptance_setup.rb
Labels: enhancement

#189 FreeIPA/LDAP provider related regression fixes
  lib/puppet/provider/keycloak_realm/kcadm.rb
  lib/puppet/type/keycloak_realm.rb
  manifests/freeipa_user_provider.pp
  spec/unit/puppet/type/keycloak_realm_spec.rb
Labels: enhancement
